# Generated by Django 6.0.3 on 2026-03-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
