# Generated by Django 6.0.3 on 2026-03-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_ai_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_model',
            field=models.CharField(default='gemini-2.5-flash', max_length=50),
        ),
    ]
